Feature/jc19 256 pagination
saritasa-nest/camp-js-2022-artem-timofeev pull request #3
Opened 2022-02-06 14:41 UTC by ArtyomTimofeev

2022-02-07 01:13 UTC, pavel-romanov8 requested changes

2022-02-07 01:13 UTC, pavel-romanov8 commented on vanilla/src/entities/models/fetchFilms.ts
> +  readonly limitDocs: number;
Isn't it strange that you make the read-only only a single field? Let's improve it, so all of them will be immutable

2022-02-07 01:13 UTC, pavel-romanov8 commented on vanilla/src/index.ts
> +const createFilmsPage = (filmsData: Film[]): void => {
You are not mutating films data inside of function anywhere. In cases like that, it would be better to declare `filmsData` as `readonly Film[]` just to make a contract for clients of the function more expressive

2022-02-07 01:13 UTC, pavel-romanov8 commented on vanilla/src/scripts/disablingTableButtons.ts
> +  if (!prevPageBtn || !nextPageBtn) {
Please, [avoid contractions](https://frontendwiki.saritasa.rocks/pages/development/principles/naming.html#avoid-contractions)

2022-02-07 01:13 UTC, pavel-romanov8 commented on vanilla/src/scripts/disablingTableButtons.ts
> +  if (!prevPageBtn || !nextPageBtn) {
If there will be `prevPageButton` this guard passes with null for `nextPageButton`. I guess it should be:
```
if (prevPageButton !== null && nextPageButton !== null)
```

2022-02-07 02:47 UTC, timofei-maximov-saritasa requested changes

2022-02-07 02:47 UTC, timofei-maximov-saritasa commented on vanilla/src/api/authorization.ts
> +    this.isUserAuthorized = true;
What if user will close popup? This user will be authorized according by your code. Please, add error handling.

2022-02-07 02:47 UTC, timofei-maximov-saritasa commented on vanilla/src/api/fetchingFilms.ts
> +  },
Do you really need this function? What is the point of your pagination, then? According to lecture, this is impossible to implement without significant trade-off, because this is not how firebase works. I would recommend to omit this function.

2022-02-07 03:50 UTC, golovachev-yaroslav approved these changes

2022-02-07 08:18 UTC, ArtyomTimofeev commented on vanilla/src/api/authorization.ts
> +    this.isUserAuthorized = true;
If the user closes the popup, authorization will be suspended and the flag will remain false, because If the popup closes, then return occurs.

2022-02-07 08:23 UTC, ArtyomTimofeev commented on vanilla/src/api/fetchingFilms.ts
> +  },
The problem is that I can't disable buttons if I don't know the number of pages in advance.

2022-02-07 10:05 UTC, panov-aleksey-saritasa commented on vanilla/src/api/fetchingFilms.ts
> +  },
@ArtyomTimofeev If you don't agree with comment from reviewer, don't resolve conversation yourself, it's a bad practice.

2022-02-08 02:23 UTC, dbitkovski requested changes

2022-02-08 02:23 UTC, dbitkovski commented on vanilla/src/api/AuthService.ts
> +  private isUserAuthorized = false;
You use `get` / `set` properties as common class fields:
```
isAuth = authService.isUserAuthorized; // get
authService.isUserAuthorized = true; // set
```
so in general we don't need to mark them either as *getter* or *setter*. For other application parts `isUserAuthorized` is one `AuthService` property.

```suggestion
private _isUserAuthorized = false;

public get isUserAuthorize(): boolen {
    this._isUserAuthorized;
}
```
I think this way it's a bit better

2022-02-08 02:23 UTC, dbitkovski commented on vanilla/src/entities/models/fetchFilms.ts
> +  readonly limitDocs: number;
Sorry, @ArtyomTimofeev have you discussed it with Pavel somehow, or why this is marked as resolved without any changes?

2022-02-08 02:23 UTC, dbitkovski commented on vanilla/src/entities/models/authorization.ts
> +export interface Authorization {
This interface has the same structure as `AuthService` but `AuthService` does not implement it. Do you need it? By the way, it's unused

2022-02-08 02:23 UTC, dbitkovski commented on vanilla/src/entities/models/fetchFilms.ts
> +export interface FetchFilms {
As I understand this is something related to `ListManager`. Probably, manager for film entities. But it's unused as well so let's remove

2022-02-08 04:51 UTC, elena-dragunova approved these changes

2022-02-08 05:58 UTC, ArtyomTimofeev commented on vanilla/src/entities/models/fetchFilms.ts
> +  readonly limitDocs: number;
I redid this functionality, made it using classes, so this comment, like the rest, has lost its meaning. Properties became immutable due to private access modifier

2022-02-08 06:03 UTC, ArtyomTimofeev commented on vanilla/src/entities/models/authorization.ts
> +export interface Authorization {
@dbitkovski the interface in this file is no longer used. I just decided not to delete the file for now

2022-02-08 11:03 UTC, dbitkovski approved these changes

2022-02-08 11:03 UTC, merged