Feature/jc19 256 more details page
saritasa-nest/camp-js-2022-artem-timofeev pull request #5
Opened 2022-02-14 21:16 UTC by ArtyomTimofeev

2022-02-15 03:22 UTC, timofei-maximov-saritasa commented on vanilla/src/api/AuthService.ts
> +    localStorage.isUserAuthorized = false;
Please, use `getItem` / `setItem` for interaction with `localStorage`.

2022-02-15 03:22 UTC, timofei-maximov-saritasa commented on vanilla/src/film-details-page/filmsDetailsPage.ts
> +const selectedFilm = filmMapper.fromDto({ ...docs.docs[0].data(), id: docs.docs[0].id });
Your `filmsDetailsPage` now knows too much about your API layer. Please, consider moving out  firebase functions and mapper from here. You can move it into separate function somewhere in your API layer. For example, you can create function `getFilmById`.

2022-02-15 03:22 UTC, timofei-maximov-saritasa commented on vanilla/src/film-details-page/scripts/getCollectionDocs.ts
> +export const getCollectionDocs = async<TDto, TModel>(ids: readonly number[], mapper: IMapperFromDto<TDto, TModel>, collectionName: string):
Please, provide documentation for your functions.

2022-02-15 04:36 UTC, golovachev-yaroslav approved these changes

2022-02-15 05:13 UTC, panov-aleksey-saritasa commented on vanilla/src/entities/models/film.ts
> +  readonly uniqHashId: string;
And isn't ids are unique by default? Why do you specify it?

2022-02-15 05:13 UTC, panov-aleksey-saritasa commented on vanilla/src/entities/.eslintrc.json
> +}
Why did turn off rule related to `any` 😟 ?

2022-02-15 05:13 UTC, panov-aleksey-saritasa commented on vanilla/src/entities/.eslintrc.json
> +}
FYI, you could add rules for specific folder from your root config, like this:
```json
  "overrides": [
    {
      "files": ["*.ts"],
      ...
    },
    {
      "files": ["**/entities/*"],
      "parserOptions": {
        "project": ["./tsconfig.json"],
        "createDefaultProgram": true
      },
      "extends": ["@chernodub/eslint-config"],
      "rules": {
        "@typescript-eslint/no-explicit-any": 0,
        "linebreak-style": 0,
        "@typescript-eslint/naming-convention": 0
      }
    }
  ]
```

2022-02-15 05:13 UTC, panov-aleksey-saritasa commented on vanilla/src/film-details-page/index.html
> +          <h3 class="mdl-layout-title">Films Catalogue</h3>
Shouldn't it be `h1`?

2022-02-15 05:13 UTC, panov-aleksey-saritasa commented on vanilla/src/film-details-page/scripts/getNamesOfCollectionItems.ts
> +};
Missing `JSDoc`. It's a function too, right? You could add `eslint` rule about `JSDoc` for arrow functions too or use `function declaration` syntax instead

2022-02-15 05:13 UTC, panov-aleksey-saritasa commented on vanilla/src/index.html
> +                <option selected value="fields.title">Title</option>
Is `fields.` something related to `Firebase`? I think UI should not know about such things.

2022-02-15 09:56 UTC, pavel-romanov8 requested changes

2022-02-15 09:56 UTC, pavel-romanov8 commented on vanilla/src/api/AuthService.ts
> +  public set setIsUserAuthorized(isUserAuthFlag: boolean) {
If you specify something as a setter you should work with it like with fields. That means that naming should also be like for fields, but here you are naming it as a function.

What is the point of naming it with the `set` prefix since we already declare it like a setter?

2022-02-15 09:56 UTC, pavel-romanov8 commented on vanilla/src/api/AuthService.ts
> +   * @param isUserAuthFlag - Flag indicating whether the user is logged in (true/false).
There is no need to specify the type domain(true/false). It is already obvious that the `boolean` type can only have 2 possible values.

2022-02-15 09:56 UTC, pavel-romanov8 commented on vanilla/src/api/AuthService.ts
> +  public get getIsUserAuthorized(): boolean {
Same with prefixes

2022-02-15 09:56 UTC, pavel-romanov8 commented on vanilla/src/css/index.css
> +  background-color: white;
Please, use custom properties for styling

2022-02-15 09:56 UTC, pavel-romanov8 commented on vanilla/src/css/index.css
> +}
Add an empty line after closing brackets and check your auto-formatter for CSS files

2022-02-15 09:56 UTC, pavel-romanov8 commented on vanilla/src/entities/mappers/charactersMappers.ts
> +export namespace characterMappers {
Please, call your namespaces in `PascalCase`

2022-02-15 09:56 UTC, pavel-romanov8 commented on vanilla/src/film-details-page/scripts/getCollectionDocs.ts
> +  const flatArray = docs.flatMap(items => items.map(dto => mapper.fromDto(dto)));
Redundant variable, you can return `docs.flatMap` right away

2022-02-15 09:56 UTC, pavel-romanov8 commented on vanilla/src/film-details-page/scripts/getCollectionRef.ts
> +export function getCollectionRef<TDto>(collectionName: string): CollectionReference<TDto> {
Please, provide typing for `collectionName` so the clients of the function know what options do they have. You can add union type with all possible values like: `CollectionName = 'films' | 'planets' ...etc.`

2022-02-15 09:56 UTC, pavel-romanov8 commented on vanilla/src/film-details-page/scripts/getNamesOfCollectionItems.ts
> +export const getNamesOfCollectionItems = (collectionItems: DocumentData[]): string => {
If you are not mutating array argument it is better to declare it as read-only to make contracts more clear for the function clients

2022-02-15 09:56 UTC, pavel-romanov8 commented on vanilla/src/film-details-page/scripts/getNamesOfCollectionItems.ts
> +  const collectionItemsNamesWithSpaces = collectionItemsNames.join(', ');
Redundant variable

2022-02-15 09:56 UTC, pavel-romanov8 commented on vanilla/src/film-details-page/scripts/getNamesOfCollectionItems.ts
> +  const collectionItemsNamesWithSpaces = collectionItemsNames.join(', ');
You can write it in one line:
```
return collectionItems.map(item => item.name).join(', ');
```

2022-02-15 09:56 UTC, pavel-romanov8 commented on vanilla/src/utils/services.ts
> +export const isUserAuthorized = (): boolean => JSON.parse(localStorage.isUserAuthorized);
We already have `getIsUserAuthorized` in `AuthService` why do we need to duplicate it here?

2022-02-15 09:56 UTC, pavel-romanov8 commented on vanilla/src/film-details-page/scripts/getSlicedArrayOfIds.ts
> +  const idsArray = ids;
What is the purpose of the variable?

2022-02-15 09:56 UTC, pavel-romanov8 commented on vanilla/src/film-details-page/scripts/getCollectionDocs.ts
> +  const slicedIdsArr = getSlicedArrayOfIds(ids, 10);
Please, move `10` to a constant with name like `PORTION_SIZE`

2022-02-15 09:56 UTC, pavel-romanov8 commented on vanilla/src/film-details-page/filmsDetailsPage.ts
> +  await filmsList.deleteItemOfCollection(selectedFilm.uniqHashId);
If we get an error at this stage user won't be redirected back and the delete button will still be disabled. I think it is not a very good UX

2022-02-15 09:56 UTC, pavel-romanov8 commented on vanilla/src/film-details-page/filmsDetailsPage.ts
> +  window.history.back();
What if I enter the page details directly without visiting your main page? You will redirect me back to another site?

2022-02-15 09:56 UTC, pavel-romanov8 commented on vanilla/src/film-details-page/filmsDetailsPage.ts
> +  window.history.back();
Same thing with navigation. I think it is better to redirect user to back for authentication

2022-02-15 09:56 UTC, pavel-romanov8 commented on vanilla/src/film-details-page/filmsDetailsPage.ts
> +const filmId = Number(params.get('id'));
`params.get` [can return null](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/get). Please consider this case

2022-02-16 04:55 UTC, gevorg-gevorgyan-saritasa requested changes

2022-02-16 04:55 UTC, gevorg-gevorgyan-saritasa commented on vanilla/src/api/AuthService.ts
> +    localStorage.isUserAuthorized = this.isUserAuthorized;
Please, use `getItem` / `setItem` methods for `localStorage`

2022-02-16 07:54 UTC, ArtyomTimofeev commented on vanilla/src/index.html
> +                <option selected value="fields.title">Title</option>
@panov-aleksey-saritasa do you mean i need to make a separate mapper for that?

2022-02-16 13:59 UTC, panov-aleksey-saritasa commented on vanilla/src/index.html
> +                <option selected value="fields.title">Title</option>
@ArtyomTimofeev you should handle that in your Firebase API layer, how it would be implemented, it's up to you :)

2022-02-17 11:45 UTC, elena-dragunova approved these changes

2022-02-17 13:48 UTC, pavel-romanov8 requested changes

2022-02-17 13:48 UTC, pavel-romanov8 commented on vanilla/src/api/AuthService.ts
> +  public set isUserAuthorized(isUserAuthFlag) {
Please, always specify the type of parameters even if it can be automatically inferred. That way we make function signature more explicit

2022-02-17 13:48 UTC, pavel-romanov8 commented on vanilla/src/api/AuthService.ts
> +    return JSON.parse(localStorage.isUserAuthorized);
This workflow can be simplified to:
```
if (!localstorage.isUserAuthorized) {
  local.storage.isUserAuthorized = false;
  return false;
}
return true;
 
```

2022-02-17 13:48 UTC, pavel-romanov8 commented on vanilla/src/api/AuthService.ts
> +  private defaultIsUserAuthorized = false;
I don't see a reason for creating this field since it is used only in a single method (property) and it can be scoped to it

2022-02-17 13:48 UTC, pavel-romanov8 commented on vanilla/src/entities/DTOs/characterDTO.ts
> +    /** Eye color, can be array divided by ",". */
Your docs and your types are telling different things. From type declaration, i see that this field can only be a `string`, but in docs, i see that it can also be an `array` of something. Please, either improve your documentation or type declaration

2022-02-17 13:48 UTC, pavel-romanov8 commented on vanilla/src/entities/DTOs/characterDTO.ts
> +    readonly hair_color: string;
Same thing with documentation

2022-02-17 13:48 UTC, pavel-romanov8 commented on vanilla/src/entities/models/character.ts
> +  readonly skinColor: readonly string[];
Again, confusing documentation. What does it mean 'can be an array'? From type declaration, i see that it can be **only** array of strings

2022-02-17 13:48 UTC, pavel-romanov8 commented on vanilla/src/entities/types/collectionNameType.ts
> +export type CollectionName = 'films' | 'planets' | 'people';
There is no need to specify in the filename that this is a type because you don't have this postfix in the actual type. It can be named just `collectionName`

2022-02-17 13:48 UTC, pavel-romanov8 commented on vanilla/src/film-details-page/filmsDetailsPage.ts
> +if (!filmId) {
This check is not enough for a simple reason. You can have an actual film with id equals 0 and `Number(null)` will return a 0. You are not considering those cases and that may lead to a confusing UX. Please, improve the logic for such cases

2022-02-17 13:48 UTC, pavel-romanov8 commented on vanilla/src/film-details-page/filmsDetailsPage.ts
> +  await filmsList.deleteItemOfCollection(selectedFilm.firebaseId).finally(() => {
Please, don't mix approaches to work with promises. We can use `finally` in that way only for `thenable` objects, therefore we are relying on `thenable` explicitly. At the same time, you are using `async/away`. If you want to have `finally` block it is better to declare it like this:
```
try {
 ...
} finally {
  ...
}
```
That way we are not explicitly relaying on `thenable` objects and working in `asyn/away` way

2022-02-21 03:14 UTC, chernodub requested changes

2022-02-21 03:14 UTC, chernodub commented on vanilla/src/css/index.css
> +  float: right;
1. Please don't use floats for positioning elements that are not supposed to be wrapped by text, it's mentally deprecated and hardly maintained. Please use flexboxes/grids for aligning stuff
2. Also, [avoid contractions](https://frontendwiki.saritasa.rocks/pages/development/principles/naming.html#avoid-contractions) for class/variable/whatever names
3. Make sure you stick to the BEM methodology. It is obvious from the name, that this class is related to some film-page container. This way, as an example, we could have a `.film-form` **block** and `.film-form__delete-button` **element**. This is especially useful when you use global styling 💡
4. Consider moving the button positioning logic to a container's style block (`.film-form`). As a rule of thumb, the element should not be responsible for positioning itself within a container. But if it is not avoidable, always stick to the BEM-element naming (`.film-form__delete-button`) so that it would be obvious to which container it's related to.

2022-02-21 03:14 UTC, chernodub commented on vanilla/src/entities/.eslintrc.json
> +        "@typescript-eslint/naming-convention": 0
This should only be overridden for mappers and DTOs not for all the entities

2022-02-21 03:14 UTC, chernodub commented on vanilla/src/entities/.eslintrc.json
> +        "linebreak-style": 0,
Why this was turned off? If you use Windows machine and your line breaks messing with you, please use LF (linux-style) only and resolve the issue, instead of turning off the rule.

2022-02-21 03:14 UTC, chernodub commented on vanilla/src/entities/DTOs/characterDTO.ts
> +  readonly fields: {
Consider moving out this generic wrapper `{fields, model, pk}` into a separate interface in order to reuse it across your app

2022-02-21 03:14 UTC, chernodub commented on vanilla/src/entities/DTOs/planetDTO.ts
> +    /** Creation date "2014-12-20T17:30:50.416Z". */
`"2014-12-20T17:30:50.416Z"` should marked under `@example` tag

2022-02-21 03:14 UTC, chernodub commented on vanilla/src/entities/DTOs/planetDTO.ts
> +    /** Population. */
Please try to be more specific in your docstring. Is it the number of people living on this planet, is it a tag-word describing the population?

2022-02-21 03:14 UTC, chernodub commented on vanilla/src/entities/mappers/charactersMappers.ts
> +  export function fromDto(dto: CharacterDTO): Character {
Please consider creating a generic interface that would aggregate `toDto` and `fromDto` methods within itself, this way you could reuse the function signatures and their docstrings

2022-02-27 11:46 UTC, closed without merging