Feature/jc19 285 table view
saritasa-nest/camp-js-2022-artem-timofeev pull request #6
Opened 2022-03-10 15:04 UTC by ArtyomTimofeev

2022-03-14 09:15 UTC, viktor-sakhno-saritasa commented on angular/src/app/core/services/mappers/film.mapper.ts
> +  ]);
I think you can use [Record](https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeys-type) for this.

2022-03-14 09:15 UTC, viktor-sakhno-saritasa commented on angular/src/app/features/films/films-page/films-page.component.html
> +      [matSortDisabled]="!!searchControl.value"
```suggestion
      [matSortDisabled]="searchControl.value"
```

2022-03-14 09:15 UTC, viktor-sakhno-saritasa commented on angular/src/app/shared/components/navbar/navbar.component.html
> +    <button
Add type

2022-03-14 09:15 UTC, viktor-sakhno-saritasa commented on angular/src/app/shared/components/navbar/navbar.component.html
> +  <button
Same as above

2022-03-14 10:36 UTC, ArtyomTimofeev commented on angular/src/app/features/films/films-page/films-page.component.html
> +      [matSortDisabled]="!!searchControl.value"
here it is necessary to cast the value to a boolean type

2022-03-15 18:35 UTC, ArtyomTimofeev commented on angular/src/app/core/services/mappers/film.mapper.ts
> +  ]);
I need a mapper here

2022-03-16 06:23 UTC, viktor-sakhno-saritasa commented on angular/src/app/features/films/films-page/films-page.component.html
> +      [matSortDisabled]="!!searchControl.value"
You can make it more explicit like `searchControl.value !== ''`

2022-03-16 06:24 UTC, panov-aleksey-saritasa requested changes

2022-03-16 06:24 UTC, panov-aleksey-saritasa commented on angular/src/app/features/films/films-page/films-page.component.ts
> +  public readonly displayedColumns: string[] = ['title', 'episodeId', 'producer', 'releaseDate'];
Missing `readonly` for array

2022-03-16 06:24 UTC, panov-aleksey-saritasa commented on angular/src/app/shared/components/navbar/navbar.component.html
> +<ng-template #elseCase>
You should use more concrete and semantically correct names for template variables

2022-03-16 06:24 UTC, panov-aleksey-saritasa commented on angular/src/app/features/films/films-page/films-page.component.html
> +      [matSortDisabled]="!!searchControl.value"
[wiki](https://frontendwiki.saritasa.rocks/pages/development/languages/typescript.html#no-implicit-hacks)

2022-03-16 06:24 UTC, panov-aleksey-saritasa commented on angular/src/app/core/services/mappers/film.mapper.ts
> +    const sortFiled = sortConfig.active as keyof Film;
typo 'sortFiled'

2022-03-16 06:24 UTC, panov-aleksey-saritasa commented on angular/src/app/core/services/mappers/film.mapper.ts
> +  ]);
You could use `Record` for mapping things too, since it's key-value data structure

2022-03-16 06:24 UTC, panov-aleksey-saritasa commented on angular/src/app/features/films/films-page/films-page.component.ts
> +      debounceTime(100),
Can't you merge sort and pagination configs into one object? Since anyway they both responsible for filtering stuff

2022-03-16 06:24 UTC, panov-aleksey-saritasa commented on angular/src/app/core/services/films.service.ts
> +  public addFilm(film: FilmDto): Observable<string> {
You shouldn't force consumer of you service to map domain entities to dto, so `FilmDto` type is incorrect here

2022-03-16 06:24 UTC, panov-aleksey-saritasa commented on angular/src/app/core/services/films.service.ts
> +  public addFilm(film: FilmDto): Observable<string> {
Consider mapping Film entity to dto in service instead

2022-03-16 06:24 UTC, panov-aleksey-saritasa commented on angular/src/app/core/services/films.service.ts
> +  public getFilmById(id: string): Observable<Film> {
You could use `Film['id']` type instead of `string`

2022-03-16 06:24 UTC, panov-aleksey-saritasa commented on angular/src/app/features/films/films-page/films-page.component.ts
> +      }),
Please, try to make your side-effects [explicit](https://frontendwiki.saritasa.rocks/pages/development/angular/practices.html#make-your-side-effects-explicit)

2022-03-16 06:24 UTC, panov-aleksey-saritasa commented on angular/src/app/features/films/films-page/films-page.component.ts
> +    debounceTime(1000),
Isn't 1 second duration for debounce is too much 😟 ? And anyway I recommend you creating some `DEFAULT_DEBOUNCE_TIME` constant for this

2022-03-16 06:44 UTC, elena-dragunova approved these changes

2022-03-16 06:53 UTC, timofei-maximov-saritasa requested changes

2022-03-16 06:53 UTC, timofei-maximov-saritasa commented on angular/src/app/core/services/authentication.service.ts
> +  }
If you are not going to use `UserCredential`, then you can do something like this:
```ts
return defer(() => signInWithPopup(this.auth, provider)).pipe(mapTo(void 0));
``` 
And `login` method will have `Observable<void>` as return type.

Otherwise, create model for your user

2022-03-16 06:53 UTC, timofei-maximov-saritasa commented on angular/src/app/core/services/films.service.ts
> +    private afs: AngularFirestore,
Do not forget to add `readonly`

2022-03-16 06:53 UTC, timofei-maximov-saritasa commented on angular/src/app/core/services/films.service.ts
> +   * Function to get data of films collection.
You can omit word `Function` in your docs. Just describe what this method is doing. For example: `Gets films ...`

2022-03-16 06:53 UTC, timofei-maximov-saritasa commented on angular/src/app/core/services/films.service.ts
> +  private getQueryFunc(pageConfig: PageEvent, sortConfig: Sort, searchValue: string): QueryFn {
You can omit `Func` in method name

2022-03-16 06:53 UTC, timofei-maximov-saritasa commented on angular/src/app/core/services/films.service.ts
> +          .where(TITLE_PROPERTY, '<=', `${searchValue}${VERY_BIG_SYMBOL}`)
What does it mean `VERY_BIG_SYMBOL`, it looks like a bad name for a variable.

2022-03-16 06:53 UTC, timofei-maximov-saritasa commented on angular/src/app/core/services/mappers/film.mapper.ts
> +  }
I don't see a case, where you can get `null` from this method.

2022-03-16 06:53 UTC, timofei-maximov-saritasa commented on angular/src/app/features/films/films-page/films-page.component.html
> +<div ngClass="films-page">
We don't use for static classes `ngClass`, use native `class` attribute instead. You can read more [here](https://angular.io/guide/built-in-directives#using-ngclass-with-an-expression)

2022-03-16 06:53 UTC, timofei-maximov-saritasa commented on angular/src/app/features/films/films-page/films-page.component.ts
> +  public readonly displayedColumns: string[] = ['title', 'episodeId', 'producer', 'releaseDate'];
Add `readonly` for array

2022-03-16 06:53 UTC, timofei-maximov-saritasa commented on angular/src/app/features/films/films-page/films-page.component.html
> +      [pageSizeOptions]="[6, 3, 2]"
Do you really want to keep it in your template, instead of component? You have `defaultPageConfig` where you define your page size, I think, those things are related

2022-03-16 06:57 UTC, timofei-maximov-saritasa commented on angular/src/app/core/utils/constants.ts
> +export const VERY_BIG_SYMBOL = '\uf8ff';
According to [firebase docs](https://firebase.google.com/docs/database/rest/retrieve-data):
The \uf8ff character used in the query above is a very high code point in the Unicode range. Because it is after most regular characters in Unicode, the query matches all values that start with a b.

2022-03-16 07:43 UTC, ArtyomTimofeev commented on angular/src/app/core/services/mappers/.eslintrc.json
> +}
this is a rule in the global file .eslintrc.json doesn't work. So now I got rid of the duplication, but left the local file.

2022-03-16 09:52 UTC, ArtyomTimofeev commented on angular/src/app/features/films/films-page/films-page.component.ts
> +      debounceTime(100),
In this case, it turns out a very complicated code like this
![image](https://user-images.githubusercontent.com/81982703/158563260-aa781a7c-75e3-449c-bfd1-85215efa2a74.png)
I think it's not very good

2022-03-16 09:53 UTC, ArtyomTimofeev commented on angular/src/app/features/films/films-page/films-page.component.ts
> +      debounceTime(100),
but I can do it any way

2022-03-16 13:42 UTC, dbitkovski commented on angular/src/app/core/services/authentication.service.ts
> +  }
More often we make these methods async and return `Observable` to be able to perform some actions after successful log in / out. Consider using the same approach.
The most obvious case is to redirect a user after one of these operations

2022-03-17 03:47 UTC, chernodub commented
@ArtyomTimofeev please never leave such commits in your pull requests, use git reset or squash 
<img width="200" alt="image" src="https://user-images.githubusercontent.com/37013688/158732988-5deca527-7530-4b53-90ee-e0b8be8f5e33.png">

2022-03-17 04:41 UTC, chernodub requested changes

2022-03-17 04:41 UTC, chernodub commented on angular/src/app/core/services/films.service.ts
> +      if (!sortQuery?.direction) {
Why not just use `else` ?

2022-03-17 04:41 UTC, chernodub commented on angular/src/app/core/services/films.service.ts
> +        return ref.limit(pageSize)
`defaultQuery` could be used here. Also, it's too generic name for the variable, consider using something more specific, that would represent it's limit-relation

2022-03-17 04:41 UTC, chernodub commented on angular/src/app/core/services/films.service.ts
> +  public addFilm(film: Film): Observable<DocumentReference<FilmDto>> {
@ArtyomTimofeev https://frontendwiki.saritasa.rocks/pages/development/angular/architecture.html

2022-03-17 04:41 UTC, chernodub commented on angular/src/app/core/services/mappers/.eslintrc.json
> +        "linebreak-style": 0,
Why turning off the `linebreak-style`? It's there for a reason, all of thelines must end with LF, if you're using a Windows machine, you may experience issues with this, please fix it

2022-03-17 04:41 UTC, chernodub commented on angular/src/app/core/services/mappers/dto/film.dto.ts
> +    readonly producer: string;
Actually, if I'm not mistaken it's a string containing a list of producer names

2022-03-17 04:41 UTC, chernodub commented on angular/src/app/core/services/mappers/film.mapper.ts
> +  direction: OrderByDirection | '';
What's the point of having a `''` as a value here, what does it represent? You should always document implicit behavior (either via code or a docstring).

2022-03-17 04:41 UTC, chernodub commented on angular/src/app/core/services/mappers/film.mapper.ts
> +  activeField: string;
Consider making it `readonly` property in case it's not going to be mutated

2022-03-17 04:41 UTC, chernodub commented on angular/src/app/core/services/mappers/film.mapper.ts
> +type sortFieldsNames = 'releaseDate' | 'episodeId' | 'title' | 'producer';
We use PascalCase for naming classes, interfaces, types https://frontendwiki.saritasa.rocks/pages/development/principles/naming.html#naming-convention

2022-03-17 04:41 UTC, chernodub commented on angular/src/app/core/services/mappers/film.mapper.ts
> +  /** From Dto to Model.
Please make sure your formatting is fixed here

2022-03-17 04:41 UTC, chernodub commented on angular/src/app/core/services/mappers/film.mapper.ts
> +  /** From Dto to Model.
This is the correct format for JSDoc:
```js
/**
 * Does something.
 * @param parameter Some parameter.
 */
```

2022-03-17 04:41 UTC, chernodub commented on angular/src/app/core/utils/constants.ts
> +export const DEFAULT_DEBOUNCE_TIME = 1000;
Consider namespacing your constants. Now they are too mixed up, DTO-related and UI-related should definitely not be in the same place

2022-03-17 04:41 UTC, chernodub commented on angular/src/app/features/films/films-page/films-page.component.css
> +.films-page__sw-table table {
When using BEM, we don't use element tags for styling

2022-03-17 04:41 UTC, chernodub commented on angular/src/app/features/films/films-page/films-page.component.html
> +      aria-label="SW Films data table"
Consider using `caption` tag instead

2022-03-17 04:41 UTC, chernodub commented on angular/src/app/features/films/films-page/films-page.component.html
> +  <div>
Why do you need an empty div here? As far as I can see it's not styled, and `mat-form-field` is already a block by default

2022-03-17 04:41 UTC, chernodub commented on angular/src/app/features/films/films-page/films-page.component.html
> +      [matSortActive]="(tableConfig$ | async)?.sortConfig?.active ?? 'title'"
To make sure your strings are type-checked, please put them to typed class properties

2022-03-17 04:41 UTC, chernodub commented on angular/src/app/features/films/films-page/films-page.component.html
> +      (page)="($event); onPaginateChange($event)"
`($event);` seems useless here 🤔

2022-03-17 04:41 UTC, chernodub commented on angular/src/app/features/films/films-page/films-page.component.ts
> +  pageSizeOptions: number[];
[Pls make these interfaces and their properties immutable](https://frontendwiki.saritasa.rocks/pages/development/languages/typescript.html#promote-immutability)

2022-03-17 04:41 UTC, chernodub commented on angular/src/app/core/services/films.service.ts
> +import { TableConfig } from 'src/app/features/films/films-page/films-page.component';
As far as I understand, this entity is needed to configure Material Table, so, your domain service implicitly depends on UI layer, which is wrong, domain never knows/imports anything about/from the UI

2022-03-17 04:41 UTC, chernodub commented on angular/src/app/features/films/films-page/films-page.component.ts
> +  public readonly films$: Observable<Film[]>;
Please, [operate with immutable data in streams](https://frontendwiki.saritasa.rocks/pages/development/angular/practices.html#operate-with-immutable-data-in-streams)

2022-03-17 04:41 UTC, chernodub commented on angular/src/app/features/films/films-page/films-page.component.ts
> +          this.resetPagination();
Consider making your side effects more explicit. https://frontendwiki.saritasa.rocks/pages/development/angular/practices.html#make-your-side-effects-explicit

Also, I'd recommend to research CQS techniques

2022-03-17 04:41 UTC, chernodub commented on angular/src/app/features/films/films-page/films-page.component.ts
> +  private readonly searchValue$ = this.searchControl.valueChanges.pipe(
Are you sure you need this to be a class-scoped property? As far as I can see you only use it once in a constructor

2022-03-17 04:41 UTC, chernodub commented on angular/src/app/features/films/films-page/films-page.component.ts
> +   */
Please revise your docstring for the whole codebase, I mentioned the correct format before.

2022-03-17 04:41 UTC, chernodub commented on angular/src/app/features/films/films-page/films-page.component.ts
> +    if (pageEvent.pageSize !== this.tableConfig$.value.pageConfig.pageSize) {
Why not simply use `else` ?

2022-03-17 04:41 UTC, chernodub commented on angular/src/app/shared/components/navbar/navbar.component.html
> +  <span>SW Films</span>
This is usually a link that navigates a user to a main page, it's a standard UX practice which we promote

2022-03-17 12:17 UTC, ArtyomTimofeev commented on angular/src/app/core/services/films.service.ts
> +      if (!sortQuery?.direction) {
Becouse I get error "Unnecessary 'else' after 'return' ", but I want to wrap a block of code in a condition to improve the readability and understandability of the code

2022-03-17 12:29 UTC, ArtyomTimofeev commented on angular/src/app/core/services/mappers/.eslintrc.json
> +        "linebreak-style": 0,
if I remove this rule I get this problem 
![image](https://user-images.githubusercontent.com/81982703/158808643-580fd99c-6fee-41d3-b36b-25d9a053dd69.png)

2022-03-17 12:35 UTC, ArtyomTimofeev commented on angular/src/app/core/services/mappers/.eslintrc.json
> +        "linebreak-style": 0,
I may to use this rule: linebreak-style: ["error", "windows"] , but then I'll have to remove/add it depending on which OS I'm working

2022-03-17 12:37 UTC, ArtyomTimofeev commented on angular/src/app/core/services/mappers/dto/film.dto.ts
> +    readonly producer: string;
No, it's just a string)
![image](https://user-images.githubusercontent.com/81982703/158809995-ef0c36a7-b1f3-47d4-838b-9e9d34a346c3.png)

2022-03-21 03:53 UTC, panov-aleksey-saritasa requested changes

2022-03-21 03:53 UTC, panov-aleksey-saritasa commented on angular/src/app/core/services/mappers/film.mapper.ts
> +type SortFieldsNamesDto = 'release_date' | 'episode_id' | 'title' | 'producer';
Consider using [Pick](https://www.typescriptlang.org/docs/handbook/utility-types.html#picktype-keys) for this. With this if the properties would be changed, 'TypeScript' could inform you about it

2022-03-21 03:53 UTC, panov-aleksey-saritasa commented on angular/src/app/core/utils/constants.ts
> +export const DEFAULT_DEBOUNCE_TIME = 1000;
I don't see this issue being fixed, why resolve then?

2022-03-21 03:53 UTC, panov-aleksey-saritasa commented on angular/src/app/features/films/films-page/films-page.component.ts
> +  private onDestroy = new ReplaySubject(1);
missing `readonly` and `$` suffix, it's `Observable` too, isn't it?

2022-03-21 03:53 UTC, panov-aleksey-saritasa commented on angular/src/app/features/films/films-page/films-page.component.ts
> +    this.tableConfig$ = new BehaviorSubject<TableConfig>(this.defaultTableConfig);
You can initialize behavior subjects right away, not sure why you are doing it inside contructor

2022-03-21 03:53 UTC, panov-aleksey-saritasa commented on angular/src/app/features/films/films-page/films-page.component.ts
> +  private onDestroy = new ReplaySubject(1);
You could use `Subject<void>` for this

2022-03-21 03:53 UTC, panov-aleksey-saritasa commented on angular/src/app/features/films/films-page/films-page.component.ts
> +  }
for `takeUntil` to work it's needed for provided observable to emit at least one value ([source](https://www.learnrxjs.io/learn-rxjs/operators/filtering/takeuntil))

2022-03-21 03:53 UTC, panov-aleksey-saritasa commented on angular/src/app/features/films/films-page/films-page.component.ts
> +  }
to fix this, use
```ts
this.onDestroy.next();
this.onDestroy.complete();
```
instead

2022-03-21 03:53 UTC, panov-aleksey-saritasa commented on angular/src/app/shared/components/navbar/navbar.component.ts
> +  private onDestroy = new ReplaySubject(1);
Same problem with `onDestroy`

2022-03-23 07:13 UTC, ArtyomTimofeev commented on angular/src/app/core/services/mappers/film.mapper.ts
> +type SortFieldsNamesDto = 'release_date' | 'episode_id' | 'title' | 'producer';
I think this is not necessary, since Pick will select duplicate fields, but what about non-duplicate ones? I think it will complicate the code

2022-03-23 07:21 UTC, ArtyomTimofeev commented on angular/src/app/features/films/films-page/films-page.component.ts
> +    this.tableConfig$ = new BehaviorSubject<TableConfig>(this.defaultTableConfig);
I do this so that private and public properties are grouped

2022-03-24 09:10 UTC, panov-aleksey-saritasa commented on angular/src/app/features/films/films-page/films-page.component.ts
> +    resetPaginationSideEffect$.subscribe();
FYI, it's a good practice to combine your side-effects into single `merge`, so you wouldn't have to write `subscribe` and `takeUntil` more than once

2022-03-24 09:10 UTC, panov-aleksey-saritasa commented on angular/src/app/features/films/films-page/films-page.component.ts
> +    resetPaginationSideEffect$.subscribe();
In your case you have one side-effect, but if there would be more side-effects it would come in handy

2022-03-24 09:10 UTC, panov-aleksey-saritasa commented on angular/src/app/shared/components/navbar/navbar.component.ts
> +  private onDestroy$ = new Subject<void>();
Missing `readonly`

2022-03-24 09:11 UTC, panov-aleksey-saritasa commented on angular/src/app/features/films/films-page/films-page.component.ts
> +  private onDestroy$ = new Subject<void>();
Missing `readonly`

2022-03-24 09:17 UTC, panov-aleksey-saritasa commented on angular/src/app/core/services/mappers/film.mapper.ts
> +type SortFieldsNamesDto = 'release_date' | 'episode_id' | 'title' | 'producer';
What do you mean by `diplicate fields` and `non-duplicate fields`?
What I proposed is to use `Pick` like this: `type SortFieldsNames = keyof Pick<Film, 'releaseDate' | 'episodeId' | 'title' | 'producer'>;`

2022-03-24 09:28 UTC, chernodub commented on angular/src/app/core/services/mappers/.eslintrc.json
> +        "linebreak-style": 0,
https://stackoverflow.com/questions/48692741/how-can-i-make-all-line-endings-eols-in-all-files-in-visual-studio-code-unix @ArtyomTimofeev

2022-03-24 09:36 UTC, chernodub commented on angular/src/app/core/services/mappers/dto/film.dto.ts
> +    readonly producer: string;
Yeah, that's what I'm saying -- _string containing a list of producer names_, you better specify this in the doc :)

2022-03-24 09:49 UTC, chernodub approved these changes

2022-03-24 09:49 UTC, chernodub commented on angular/src/app/core/models/table-config.ts
> +import { Sort } from '@angular/material/sort';
Angular Material is a UI-layer and your domain layer should never know anything about UI. Please consider either moving this model out of core (and never rely on it in any of core models). In order to get more knowledge about our architecture approach, check out our [architecture page in wiki](https://frontendwiki.saritasa.rocks/development/angular/architecture/)

2022-03-24 09:49 UTC, chernodub commented on angular/src/app/core/services/mappers/film.mapper.ts
> + * but matSort can return not only "asc" and "desc" but also ''.
Your domain/repository layers should never know anything about your UI lever, therefore, this hack should either be isolated in components or removed

2022-03-24 12:17 UTC, ArtyomTimofeev commented on angular/src/app/features/films/films-page/films-page.component.ts
> +    resetPaginationSideEffect$.subscribe();
If I do not initialize in the constructor, then there will be such an order of properties:
private
public
public
private
public
And I can't do anything about it, since private properties must be initialized before public and vice versa.

2022-03-24 12:28 UTC, ArtyomTimofeev commented on angular/src/app/core/services/mappers/film.mapper.ts
> +type SortFieldsNamesDto = 'release_date' | 'episode_id' | 'title' | 'producer';
Now I understand, thanks for the clarification.

2022-03-24 12:29 UTC, ArtyomTimofeev commented on angular/src/app/features/films/films-page/films-page.component.ts
> +    this.tableConfig$ = new BehaviorSubject<TableConfig>(this.defaultTableConfig);
If I do not initialize in the constructor, then there will be such an order of properties:
private
public
public
private
public
And I can't do anything about it, since private properties must be initialized before public and vice versa.

2022-03-25 08:32 UTC, merged