Feature/jc19 297 films list with auth
saritasa-nest/camp-js-2022-artem-timofeev pull request #7
Opened 2022-03-23 20:50 UTC by ArtyomTimofeev

2022-03-24 04:12 UTC, golovachev-yaroslav approved these changes

2022-03-24 10:32 UTC, timofei-maximov-saritasa requested changes

2022-03-24 10:32 UTC, timofei-maximov-saritasa commented on react/src/api/services/films.service.ts
> +type FilmsServiceReturnedData = Pick<FilmsState, 'films' | 'lastDocCursor'>;
Lets improve type name

2022-03-24 10:32 UTC, timofei-maximov-saritasa commented on react/src/api/services/films.service.ts
> +import { FilmsState } from '../../store/film/state';
It is really strange, that your service knows about `FilmsState`

2022-03-24 10:32 UTC, timofei-maximov-saritasa commented on react/src/components/AppHeader/AppHeader.tsx
> +  const loginButtonText = useAppSelector(selectLoginButtonText);
Why do you keep button text in redux? Your strore doesn't care about your UI, please fix it.

2022-03-24 10:32 UTC, timofei-maximov-saritasa commented on react/src/components/AppHeader/AppHeader.tsx
> +        <Button color="secondary" variant="contained" disabled={isAuthLoading} onClick={toggleLogin}>
Missing `type` on your button

2022-03-24 10:32 UTC, timofei-maximov-saritasa commented on react/src/components/AppHeader/index.ts
> +export { AppHeaderComponent as AppHeader } from './AppHeader';
If you are not going to use `hoc` on this component, then it is fine to name it `AppHeader`

2022-03-24 10:32 UTC, timofei-maximov-saritasa commented on react/src/features/films/components/FilmItem/FilmItem.tsx
> +export const FilmItemComponent: VFC<Props> = ({ film }) => (
If you want, you can use `memo` HOC [docs](https://reactjs.org/docs/react-api.html#reactmemo)

2022-03-24 10:32 UTC, timofei-maximov-saritasa commented on react/src/models/film.ts
> +  public readonly charactersIds: number[];
Missing `readonly` for arrays

2022-03-24 10:32 UTC, timofei-maximov-saritasa commented on react/src/store/auth/state.ts
> +  /** IsUserAuthorized flag. */
Please, improve documentation.

2022-03-24 10:32 UTC, timofei-maximov-saritasa commented on react/src/store/film/state.ts
> +  readonly films: Film[];
As we discussed earlier: our state should be normilized. It will help you manage your films in future, when you will be working on `FilmPage`.
You can read more about [here](https://redux.js.org/usage/structuring-reducers/normalizing-state-shape). Also redux-toolkit provides [great tools](https://redux-toolkit.js.org/usage/usage-guide#managing-normalized-data) to help you with normalizing

2022-03-24 18:05 UTC, ArtyomTimofeev commented on react/src/api/dtos/film.dto.ts
> +    readonly characters: number[];
If I make arrays as readonly, I get  this typescript error. How can I fix this?

2022-03-24 18:07 UTC, ArtyomTimofeev commented on react/src/api/dtos/film.dto.ts
> +    readonly characters: number[];
![image](https://user-images.githubusercontent.com/81982703/159981877-0a5a328b-d9c9-44ec-b135-86512030dee3.png)

2022-03-24 18:15 UTC, ArtyomTimofeev commented on react/src/api/dtos/film.dto.ts
> +    readonly characters: number[];
![image](https://user-images.githubusercontent.com/81982703/159983592-34ea5586-e7f4-4297-b116-24480c23b07a.png)

2022-03-25 03:01 UTC, chernodub commented on react/src/store/auth/slice.ts
> +      state.authLoading = true;
As I already recommended before, please stick to immutable state reducing

2022-03-25 06:37 UTC, timofei-maximov-saritasa commented on react/src/api/dtos/film.dto.ts
> +    readonly characters: number[];
You can read more about `readonly` with immer in [immer docs](https://immerjs.github.io/immer/typescript/)

2022-03-25 11:27 UTC, danilkukryakov approved these changes

2022-03-25 11:27 UTC, danilkukryakov commented on react/src/components/AppHeader/AppHeader.tsx
> +  const [loginButtonText, setLoginButtonText] = useState('Login');
Not sure why we need to use a state just for login button text. Seems like an over engineering to me 😄 
A better approach may be the following:
```ts
const loginButtonText = isUserAuthorized ? 'Logout' : 'Login';
```

2022-03-25 11:27 UTC, danilkukryakov commented on react/src/features/films/components/Search/Search.tsx
> +    <TextField
I guess, we can add `type="search"` to improve semantics and accessibility.

2022-03-25 11:27 UTC, danilkukryakov commented on react/src/features/films/pages/FilmsPage/FilmsPage.module.css
> +  height: 50vh;
My suggestion is not to rely on relative units for sizes (exception might be 100% or 100vh).
Maybe in this case it works fine but in rather complex layout it would be better to select another approach (e.g. flexbox based layout or something else).

2022-03-25 11:27 UTC, danilkukryakov commented on react/src/features/films/pages/FilmsPage/FilmsPage.tsx
> +          ))}
For large lists it might be useful to wrap an array in `useMemo` to reduce computations.
It may look like:
```tsx
const filmsList = useMemo(() => films.map(film => (
     <FilmItem key={film.id} film={film} />
)), [films]);

return (
  // ...
  {filmsList}
  // ...
)
```

2022-03-25 11:27 UTC, danilkukryakov commented on react/src/store/auth/slice.ts
> +          error: action.error.message,
There is no need to update state using this approach.
Redux Toolkit has `immer` built in which will handle immutability related things for us.
Now we have `[immerable]` in our models but don't use `immer` in reducers 😅 

You may revisit Redux Toolkit [docs](https://redux-toolkit.js.org/usage/immer-reducers) to find out more about `immer` usage pattern.

Here it might looks like:
```ts
.addCase(login.rejected, (state, action) => {
  state.isUserAuthorized = false;
  state.authLoading = false;
  // etc.
})
```

2022-03-25 12:10 UTC, timofei-maximov-saritasa commented on react/src/api/dtos/film.dto.ts
> +    readonly characters: number[];
@chernodub `castDraft` will work here, since Immer handles all immutable stuff for us [docs](https://immerjs.github.io/immer/typescript/#cast-utilities).

2022-03-25 12:16 UTC, ArtyomTimofeev commented on react/src/store/auth/slice.ts
> +      state.authLoading = true;
in this case, I can use assignment since the toolkit's built-in immer solves the problem of immutability

2022-03-27 09:19 UTC, pavel-romanov8 requested changes

2022-03-27 09:19 UTC, pavel-romanov8 commented on react/src/store/film/dispatchers.ts
> +    return FilmsService.fetchFilms(sortingType, searchValue);
```suggestion
  ({sortingType, searchValue}: FetchFilmsProps) => {
    return FilmsService.fetchFilms(sortingType, searchValue);
```

2022-03-27 09:19 UTC, pavel-romanov8 commented on react/src/utils/constants.ts
> +export const FILMS_DOCS_LIMIT = 7;
Please, revise the constants that you have here because some of them are being used only locally like this one. As I see, you are using it only in the `FilmService` therefore it should be placed there instead

2022-03-27 09:19 UTC, pavel-romanov8 commented on react/src/models/film.ts
> +export class Film extends Immerable {
I'm not sure that there is a point of making the `Immerable` class abstract. You don't have any abstract fields or methods, therefore it can be just plain class.

2022-03-27 09:19 UTC, pavel-romanov8 commented on react/src/utils/constants.ts
> +export const TITLE_PROPERTY = 'fields.title';
It looks like we are using such things because it is how the back-end is organized it, but we shouldn't tie ourselves to it. It would be better to create a standalone enum with those 3 fields - title, episode ID and release date and make a mapping to the model that we can easily support.

Another benefit that we can have from an approach like that is our sorting fields become typed, and we can make less error

2022-03-27 10:26 UTC, ArtyomTimofeev commented on react/src/utils/constants.ts
> +export const TITLE_PROPERTY = 'fields.title';
fixed it in another branch

2022-03-27 10:27 UTC, merged