Feature/jc19 291 management
saritasa-nest/camp-js-2022-artem-timofeev pull request #8
Opened 2022-03-27 11:00 UTC by ArtyomTimofeev

2022-03-28 02:07 UTC, panov-aleksey-saritasa requested changes

2022-03-28 02:07 UTC, panov-aleksey-saritasa commented on angular/src/app/features/films/details-film-page/details-film-page.component.css
> +}
If you are sticking to BEM, please, check its documentation once again, this selector is wrong

2022-03-28 02:07 UTC, panov-aleksey-saritasa commented on angular/src/app/core/services/mappers/dto/planet.dto.ts
> +
Consider creating helper interface that would wrap your base dto interface with 'fields', 'model', 'pk' properties

2022-03-28 02:29 UTC, panov-aleksey-saritasa commented on angular/src/app/features/films/details-film-page/details-film-page.component.ts
> +  public deleteFilm(id: string): void {
Please, add `on` prefix for event handler methods

2022-03-28 02:29 UTC, panov-aleksey-saritasa commented on angular/src/app/features/films/details-film-page/details-film-page.component.ts
> +  public deleteFilm(id: string): void {
You could use `Film['id']` instead of `string`

2022-03-28 02:29 UTC, panov-aleksey-saritasa commented on angular/src/app/features/films/details-film-page/dialog-with-film-form/dialog-with-film-form.component.css
> +}
Please, avoid tag selectors inside component styles, you could do just the same with classes

2022-03-28 02:29 UTC, panov-aleksey-saritasa commented on angular/src/app/features/films/details-film-page/dialog-with-film-form/dialog-with-film-form.component.ts
> +    if (!this.data) {
Please, avoid implicit type casting

2022-03-28 05:52 UTC, viktor-sakhno-saritasa commented on angular/src/app/features/films/details-film-page/details-film-page.component.html
> +    aria-label="Example icon button with a delete icon"
Change this label, please.

2022-03-28 06:07 UTC, viktor-sakhno-saritasa commented on angular/src/app/features/films/details-film-page/dialog-with-film-form/dialog-with-film-form.component.html
> +      [disabled]="form.invalid"
Recommend use `[disabled]=”!form.valid”`, because it is more secure than `[disabled]=”form.invalid”` . [Read more](https://itnext.io/valid-and-invalid-in-angular-forms-61cfa3f2a0cd)

2022-03-28 06:07 UTC, viktor-sakhno-saritasa commented on angular/src/app/features/films/details-film-page/details-film-page.component.ts
> +  public readonly selectedFilm$ = this.filmsService.getFilmById(this.route.snapshot.paramMap.get('id') ?? '').pipe(
I think you can use `this.route.paramMap` observable to check id param inside the component instead of passing an empty string to the service.

2022-03-28 07:13 UTC, timofei-maximov-saritasa commented on angular/src/app/features/films/details-film-page/details-film-page.component.html
> +    aria-label="Example icon button with a delete icon"
🙃️

2022-03-28 07:13 UTC, timofei-maximov-saritasa commented on angular/src/app/features/films/details-film-page/details-film-page.component.html
> +        </span>
You can use `join()` here.

2022-03-28 07:13 UTC, timofei-maximov-saritasa commented on angular/src/app/features/films/details-film-page/details-film-page.component.ts
> +    private readonly characterMapper: CharacterMapper,
Why does your component know something about mappers?

2022-03-29 11:11 UTC, ArtyomTimofeev commented on angular/src/app/core/services/mappers/dto/planet.dto.ts
> +
I removed all unnecessary fields from this model. Is this conversation still relevant?

2022-03-30 09:49 UTC, chernodub approved these changes

2022-03-30 09:49 UTC, chernodub commented on angular/src/app/features/films/details-film-page/details-film-page.component.html
> +    <mat-icon aria-hidden="true" aria-label="Add New Film">add</mat-icon>
aria-hidden will hide the element completely to assistive technology, such as screen readers and braille devices. So, your `aria-label` is useless in this case. Consider using title for button instead

2022-03-30 09:49 UTC, chernodub commented on angular/src/app/features/films/details-film-page/details-film-page.component.html
> +      <h1><strong>Title:</strong> {{ film.title }}</h1>
For styling text, use CSS only. And please revise the semantic meaning of `strong`

2022-03-30 09:49 UTC, chernodub commented on angular/src/app/features/films/details-film-page/details-film-page.component.html
> +    <div class="film-details-card__controls">
`film-details-card` block must be present if you need an element

2022-03-30 09:49 UTC, chernodub commented on angular/src/app/features/films/details-film-page/details-film-page.component.html
> +        <span>{{ names.join(", ") }}</span>
Consider leveraging semantic tags by usign `ul`

2022-03-30 09:49 UTC, chernodub commented on angular/src/app/features/films/details-film-page/dialog-with-film-form/dialog-with-film-form.component.html
> +        <mat-option *ngFor="let planet of planets" [value]="planet.id"
https://frontendwiki.saritasa.rocks/development/angular/practices#trackby

2022-03-30 20:46 UTC, merged